---
name: Deploy the presentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:latest

    name: build the presentation
    steps:
      - uses: actions/checkout@v6

      - name: build the webpage
        run: |
          dnf -y install --refresh emacs yarnpkg git
          yarn install
          emacs building-containers-in-obs.org -Q --batch -l export-init.el -f org-reveal-export-to-html --kill

      - name: copy the webpage to build
        run: |
          cp --recursive media/ build/
          cp --recursive node_modules/ build/
          cp *.html build/
          cp *.css build/

      - name: upload the build directory
        uses: actions/upload-artifact@v5
        with:
          name: build
          path: ./build

  deploy:
    name: deploy to the gh-pages branch
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v6
        with:
          name: build
          path: ./build

      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build

